// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhgwwesargguqmummmjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZ3d3ZXNhcmdndXFtdW1tbWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTAxMjgsImV4cCI6MjA2OTE4NjEyOH0.nRisauDa2AkuAC7nr4iDW2wNW33BP3fHzaTp7XSP5R8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});